# nixpacks.toml
[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci",
  "cd server && npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "cp -r dist server/"
]

[phases.start]
cmd = "cd server && node server.js"