# nixpacks.toml
[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build] 
cmds = ["npm ci", "npm run build", "cp -r dist server/"]

[phases.start]
cmd = "cd server && npm start"