# nixpacks.toml
[variables]
NODE_VERSION = "20"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "rm -rf node_modules package-lock.json",
  "npm install --no-optional",
  "npm install @rollup/rollup-linux-x64-gnu --save-dev"
]

[phases.build]
cmds = [
  "npm run build:only",
  "cp -r dist server/"
]

[phases.start]
cmd = "cd server && node server.js"